version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: phlearn/docs/requirements.txt
    - method: pip
      path: phlearn

sphinx:
  fail_on_warning: true
  configuration: phlearn/docs/source/conf.py